### ISSUE TITLE
Script recognize my launchpad as launchpad PRO

### ISSUE THREAD

**Issue by AndyV2** [nimaid/LPHK#13]
Hi,

The script recognize my genuine novation launchpad as a launchpad pro, therefore I'm unable to connect the launchpad to this script. Any ideas?

**Comment by nimaid** [comment]
Odd. Could you please open a command prompt (Win+R, "cmd", then enter) and in it type:
    cd (your LPHK directory)/utils
    python RAW_CONNECT.py
And give me the results?

**Comment by nimaid** [comment]
@AndyV2 I have pushed a commit a while ago that changed how the Launchpad version is detected. Please let me know if this fixes your issue so I can close this.

Also, partial Launchpad Pro support is in beta. Hope that works for you. :)

**Comment by AndyV2** [comment]
I'll try it out ;)

**Comment by nimaid** [comment]
@AndyV2 Did you ever find out if the new commit worked for you!

**Comment by nimaid** [comment]
@AndyV2 Please respond to this issue soon, or I will assume the previous commit resolved your issue.

**Comment by AndyV2** [comment]
Sorry that this took a while. It worked :)
