### ISSUE TITLE
PRESS and TAP are not global on windows

### ISSUE THREAD

**Issue by duncte123** [nimaid/LPHK#16]
While testing the program out on windows I noticed that the key commands like TAP, PRESS and `@SIMPLE` are only executed for the window that is currently focussed, this breaks using LPHK for stuff like controlling obs while you are streaming

**Comment by nimaid** [comment]
As per our discussion in the Discord, I am unable to reproduce this. I'll keep working with you there to see why it is not working on your computer. If anyone else is having this issue as well, please report it here.

**Comment by duncte123** [comment]
The issue has been resolved by waiting for an unpress

Script that does not work:
```
@ASYNC
PRESS ctrl
TAPf15
RELEASE ctrl
```
Script that does work:
```
@ASYNC
PRESS ctrl
PRESS f15
WAIT_UNPRESSED
RELEASE f15
RELEASE ctrl
```
