### ISSUE TITLE
LPHK on Mini?

### ISSUE THREAD

**Issue by pozzzzy** [nimaid/LPHK#2]
I absolutely love the concept of LPHK, but I only own a Launchpad Mini. Is it possible you can work towards a solution for Launchpad Mini? And if so, could I request a rough estimate on when I could use LPHK with Mini?
Thanks in advance.

Edit: I apologise, I had not read the readme thoroughly.

**Comment by nimaid** [comment]
Great news! A Patreon patron paid for me to buy a Launchpad Mini! It will ship on the 11th of Feburary.

**Comment by pozzzzy** [comment]
Awesome! Looking forward to a potential release! Don't let me down -_-
