### ISSUE TITLE
shift_r doesn't exist

### ISSUE THREAD

**Issue by TulipBalm** [nimaid/LPHK#22]
So currently I'm trying to bind vrchat gestures to my launchpad, these keybinds are:
shift+f1 through 8 for left hand
right shift+f1 through 8 for right hand

left hand works like a dream with the code:

PRESS shift
PRESS f1
WAIT_UNPRESSED
RELEASE shift
RELEASE f1

right hand however cannot be bound since when i replace shift with shift_r it comes up with an error message saying the key does not exist.

**Comment by duncte123** [comment]
Should be fixed once #35 is merged

**Comment by TulipBalm** [comment]
awesome! thanks for looking into it

**Comment by Im-Mr-Chris** [comment]
Hello, I too have experienced this same error but with " [ , ] , mouse_left , mouse_middle , mouse_right.
Not sure if it's related, just thought I'd mention it.

**Comment by duncte123** [comment]
Will be fixed in #48
