### ISSUE TITLE
Windows + L doesn't work

### ISSUE THREAD

**Issue by RubixDev** [nimaid/LPHK#27]
I tried to set up a button to lock my computer using the key combination Windows + L.
The Code I used looks like this:
`PRESS windows`
`TAP l`
`RELEASE windows`
However it didn't do anything, but when I used a combination like Win + E (for opening a file explorer) it worked just fine...

**Comment by duncte123** [comment]
Try the solution from issue #16

**Comment by RubixDev** [comment]
It still doesn't work, but a Windows error sound is played.

**Comment by duncte123** [comment]
try `cmd` instead of `windows`

**Comment by RubixDev** [comment]
hm... Still not working.

**Comment by duncte123** [comment]
Then it may be windows blocking it

**Comment by pstaszko** [comment]
I call cmd from an autohotkey script to lock my computer.
cmd /c "RunDll32.exe user32.dll,LockWorkStation"

**Comment by RubixDev** [comment]
Thanks! This method actually works!
I've heard of Autohotkey before, but never really knew what it is. Althogh it was a bit tedious to make an extra ahk script just to lock the computer, I really think it payed off.

**Comment by pstaszko** [comment]
I'm glad it worked for you. AutoHotkey is absurdly powerful. My advice for anyone doing development on Windows is to get familiar with AHK and PowerShell. My use case for LPHK would be to trigger AutoHotkey scripts that would probably communicate with an F# program over a micro HTTP service so I could get some real work done.
