### ISSUE TITLE
Does this work with the Launchpad Mini mk3?

### ISSUE THREAD

**Issue by pstaszko** [nimaid/LPHK#29]
Does this work with the Launchpad Mini mk3?

**Comment by lyiriyah** [comment]
use latest release

**Comment by Fhayt** [comment]
I tried the latest release and was able to get LPHK to connect correctly to my mini mk3. When I loaded one of the examples, only the custom buttons, Drums, Keys, and User stayed lit up but the rest of the keys were blank. The custom buttons executed the loaded scripts correctly but the rest of the buttons do nothing. Any idea why this is happening?

**Comment by duncte123** [comment]
launchpad.py (library used to connect) isn't updated to support the mk3 yet, we currently cheat and tell the library to use it as an Mk2 but that is not optimal

launchpad.py issue: https://github.com/FMMT666/launchpad.py/issues/41

**Comment by d0x7** [comment]
It does work with my Novation Launchpad Mini MK3. Someone should close this.
