### ISSUE TITLE
Auto-Importing Functions

### ISSUE THREAD

**Issue by Super99Master** [nimaid/LPHK#3]
Hello everyone,
The idea is to have a main script that at a fixed point (startup) wuold read all files in a sub-folder (/commands) and if the file has the right format (normal .py script + a specific header) it would import it as an available command/function in the LPHK language. 

The script will check for the libs that it needs to run that specific script and install it via pip.

In the header, there will be a way to rename functions.
When using an importend function you need to use the name of the file "x" and the name of the function "y".
In the LPHK script, you will need to write x.y as a command.
When importing a file, the script will create a dictionary and associate a specific command with a custom name.
Something like function['WEB_NEW']=Web.open_ new.
Thanks to this, you'll be able to use the custon name and make the LPHK script look "nicer".

**Comment by nimaid** [comment]
I have been busy with work, but have been wanting to move LPHK forward badly. I have decided to at least get this feature done within the next month because that way the community could easily write new features for LPHK in the interim between periods of development on my end. Stay tuned!

**Comment by nimaid** [comment]
Not done yet B/C of other features, but in the TODO list.
