### ISSUE TITLE
LP Mini not working.

### ISSUE THREAD

**Issue by qCamm** [nimaid/LPHK#4]
Hooked up my LP Mini and tried to connect but connection failed after many redetects.

**Comment by PastaLittleEggo** [comment]
Last I checked, this only supports the Launchpad MK2.

**Comment by nimaid** [comment]
LPHK does currently support the LP Mini, and it does work for me on both Ubuntu and Windows 10.

@qCamm Can you please give me the following info:

- What OS are you using?
- Did you [read and follow the troubleshooting section of the Readme](https://github.com/nimaid/LPHK#known-issues--troubleshooting)? What happened?
- Does your LP work well in other programs?

**Comment by qCamm** [comment]
I'm using Windows 10 and I have tried troubleshooting LPHK. Working fine on Ableton Live.

**Comment by nimaid** [comment]
@qCamm With the LP plugged in, and all other programs that could use it being terminated, could you please run utils/CONNECT_RAW.py and paste the output here?

**Comment by qCamm** [comment]
Sorry for extremely late response... how can I do this without the window immediately disappearing?

**Comment by nimaid** [comment]
@qCamm Is it "flashing" colors continuously, or did it just flash when it was plugged in? If it's doing the "fireworks" effect, it is not "connected" to the computer, it's just getting power.

Try plugging it in, then **do not move the Launchpad or the cable** at all. Please verify you can use the LP in Ableton, tyhen close ableton. Test LPHK after closing (without moving anything), but make sure you get the newest version. If this still fails, I may have to seek help from the creator of Launchpad.py.

**Comment by qCamm** [comment]
I've managed to get it working. The orange cable that came packaged with the launchpad did not work properly for some strange reason. I had replaced it and I am now able to use LPHK without a problem.

Thank you for your time and effort to help.
