### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by McFly24** [nimaid/LPHK#49]
Is there any option to autostart LPHK on PC boot load a config/layout and run it in the Background
Is there anything planed for the future?

**Comment by duncte123** [comment]
This can be done inside of your os already, for windows you just need to add a shortcut in the startup folder to make lphk boot.

**Comment by destr0yed** [comment]
Autostart is not a big deal. There just needs to be a function to automatically load a script when starting the program.
I would love to see that, keep up the great work! <3
