### ISSUE TITLE
AttributeError: module 'launchpad_py' has no attribute 'LaunchpadMk3'

### ISSUE THREAD

**Issue by reggievick** [nimaid/LPHK#54]
**Error**
AttributeError: module 'launchpad_py' has no attribute 'LaunchpadMk3'

**Solution**
Need to change the launchpad_connector.py file for the below:

Please notice that the class "LaunchpadMk3()" was renamed to "LaunchpadMiniMk3()" in 5/2020.
[](https://github.com/FMMT666/launchpad.py)

**Comment by duncte123** [comment]
This has been changed on the development branch a while ago https://github.com/nimaid/LPHK/blob/develop/utils/launchpad_connector.py#L15

**Comment by duncte123** [comment]
#53 is waiting for a review from @nimaid

**Comment by reggievick** [comment]
> #53 is waiting for a review from @nimaid

I agree, those changes look like they would correct the issue.

**Comment by duncte123** [comment]
Closing this issue as this should have been fixed
