### ISSUE TITLE
Simply assigned keys are not accepted in the game

### ISSUE THREAD

**Issue by LFSXtreme** [nimaid/LPHK#56]
Hi!
I assigned simple buttons to the launchpad.
I want to use it with the game Elite: Dangerous.

If I press the assigned keyboard shortcuts on the Launchpad in a note, then I get the result directly. This means that the inputs via the launchpad actually work like a keyboard.

However, this does not work in the game.
The game does not accept any buttons from the launchpad.

Am I missing something here?

**Comment by duncte123** [comment]
How are you running the program?

**Comment by duncte123** [comment]
Could you also send an example of the script that is not working?

**Comment by LFSXtreme** [comment]
Its just this (for example):

> PRESS t
> WAIT_UNPRESSED
> RELEASE t

So now I can spam a lot of "t" in a text editor and get a lot of "t".

: D

But the key is simply not accepted in the game. As if nothing is being pressed.

**Comment by LFSXtreme** [comment]
Commando back! I have it! Sorry!

I didn't run it in admin mode.

Thank you!

**Comment by duncte123** [comment]
Glad that the issue is now solved
