### ISSUE TITLE
Error when trying to use mouse_left or mouse_right

### ISSUE THREAD

**Issue by H0lzh4ck3r** [nimaid/LPHK#59]
When I try to use TAP/PRESS mouse_left/mouse_right it shows following error:
![image](https://user-images.githubusercontent.com/69899582/90624392-2b31d500-e218-11ea-90c3-9e7c00bfff0f.png)

**Comment by duncte123** [comment]
Duplicate of https://github.com/nimaid/LPHK/issues/52 (will not close yet as the exe's are not updated)

**Comment by duncte123** [comment]
Is this still an issue with the latest release?

**Comment by H0lzh4ck3r** [comment]
No, In the source build someone did for me it works just fine, Ill close this ticket if I can
