### ISSUE TITLE
Repeat command while button is pressed

### ISSUE THREAD

**Issue by Mongstaen** [nimaid/LPHK#67]
Hi!
Firtst of all, thank you ever so much for this project! I really appreciate this 👍 

Is there a function which allows for the command to repeat while the button is pressed?
For instance with vol_down. 

While button is pushed down, repeat @SIMPLE vol_down until button is released. 

Makes sense?

**Comment by duncte123** [comment]
this file has an example of that https://github.com/nimaid/LPHK/blob/master/user_layouts/examples/default.lpl

**Comment by Mongstaen** [comment]
Hi Duncan, 
I'm sorry but I fail to see this in that file. 
Would you mind pointing me to the correct line? :)

**Comment by duncte123** [comment]
I suggest loading it in the program and looking at one of the colored buttons in the bottom left. That way you can see the script better
