### ISSUE TITLE
multiple keys

### ISSUE THREAD

**Issue by MXML3GEND** [nimaid/LPHK#70]
could you please make it so that we can use multiple keys for tab and enter and such. that would be really awesome!

**Comment by duncte123** [comment]
What exactly do you mean by "multiple keys for tab and enter"?

**Comment by MXML3GEND** [comment]
I mean like we should be able to do 'TAB ctrl+enter' for example

**Comment by duncte123** [comment]
something like this?

```
PRESS ctrl
PRESS enter
WAIT_UNPRESSED
RELEASE_ALL
```

**Comment by MXML3GEND** [comment]
No, I think more like if I wanna output 'A'
That i can do 'TAB caps+a'

**Comment by duncte123** [comment]
That would just be the string command with a capital `A`

**Comment by MXML3GEND** [comment]
Look, I have a program that uses the hotkey ctrl+f1 to do something

**Comment by duncte123** [comment]
Then the solution I gave you before will work just fine
```
PRESS ctrl
PRESS f1
WAIT_UNPRESSED
RELEASE_ALL
```

**Comment by MXML3GEND** [comment]
ow thanks lol
