### ISSUE TITLE
Top function keys lighting up

### ISSUE THREAD

**Issue by MDproductions-dev** [nimaid/LPHK#72]
When i run the script from the development branch all the top function keys lighten up while i don't have a script set to those keys.

**Comment by duncte123** [comment]
Could you clarify and visualize what the issue is exactly?

**Comment by MDproductions-dev** [comment]
The top 8 buttons on my launchpad light up orange when running the script. I have looked through the code already but didn't find anything that would do that. Here are 2 pictures.
![launchpad pic](https://user-images.githubusercontent.com/48647949/108488609-dfccb200-72a0-11eb-8b0b-e5112d241db3.jpg)
![lphk pic](https://user-images.githubusercontent.com/48647949/108488606-de9b8500-72a0-11eb-870c-26cb6ae14f4b.png)

**Comment by duncte123** [comment]
I think that this might be a defect of your launchpad, what happens when you set a button in the top row?

**Comment by MDproductions-dev** [comment]
> I think that this might be a defect of your launchpad, what happens when you set a button in the top row?

It stays orange but the script works.

**Comment by MDproductions-dev** [comment]
If i use the normal executable this doesn't happen. Only in the development branch script wich i use cause i needed to add some features i needed.

**Comment by MDproductions-dev** [comment]
I have concluded this didn't happen on version 3.0.0 but does on 3.0.1

**Comment by MDproductions-dev** [comment]
Hmm it does happen on the prebuilt executable on version 3.0.0 but not with the script. Probably a newer version of a dependency wich wierded out my launchpad?

**Comment by MDproductions-dev** [comment]
Found the culprit! Appearently launchpad_py 9.0 wierds out my launchpad (launchpad mini mkII) downgrading to 0.8.1 resolved it!
