### ISSUE TITLE
Error in ']' and 'mouse_left'

### ISSUE THREAD

**Issue by TheKingOfAssists** [nimaid/LPHK#76]
Hi there! 
I was trying to have my mouse buttons press on commands, but it looks like the program doesn't recognise mouse_left or ']' anymore~ I tried opening the GIMP example, but that gave me all sorts of problems

How can we fix this?
Kind regards,
TKOA

**Comment by duncte123** [comment]
Please let me know the following information:

OS, LPHK version, the exact script

**Comment by TheKingOfAssists** [comment]
HI duncte! 
I'm running Windows 10 home (19041.804) 
I just downloaded the master code, so whichever version that is  (code -> download as zip)
In the examples folder, opening the gimp example will give you two errors 
"key does not exist" for "[" and another one with "mouse_left" 
the script goes "@SIMPLE ]"

Hope that helps!
Kind regards

**Comment by TheKingOfAssists** [comment]
Just found out how to download the release and it works now.
Welp, made a fool out of myself 👍 

Have a good day!

**Comment by duncte123** [comment]
hmm the code from master is the same code as the release so I don't see why that happened unless you are missing some dependencies
