### ISSUE TITLE
Problems with large scripts.

### ISSUE THREAD

**Issue by RealCountrx** [nimaid/LPHK#77]
I recently tried wrighting a long script within the program and it just crashed fully. My MK3 was still receiving data, but it wasn't doing anything. I'm using Windows 64 bit. The script contained multiple "PRESS, RELEASE, and STRING" commands.

The gray button in this layout is a part of what I was trying to make. It still crashes it as well. https://mystuff.bublup.com/ui/landing_page?item_id=001-i-2b4c006c-0c2d-4266-acff-a91a40f156d4

**Comment by duncte123** [comment]
could you attach the file instead? The page does not let me download it

**Comment by RealCountrx** [comment]
> could you attach the file instead? The page does not let me download it

@duncte123 Does not let me attach LPL files

I went to the link in a incognito window and it still let me install. The install button is on the top right.

**Comment by duncte123** [comment]
You've put in characters that LPHK cannot type

```
[files] Loaded layout D:/Windows/Downloads/MAIN LAYOUT.lpl
[scripts] (3, 1) No script running, starting script in background...
[scripts] (3, 1) Now running script...
Exception in thread Thread-744:
Traceback (most recent call last):
  File "C:\Users\dunca\Miniconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\dunca\Miniconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\LPHK\scripts.py", line 107, in run_script_and_run_next
    run_script(script_in, x_in, y_in)
  File "D:\LPHK\scripts.py", line 486, in run_script
    idx = main_logic(idx)
  File "D:\LPHK\scripts.py", line 170, in main_logic
    print("[scripts] " + coords + "    Type out string " + type_string)
  File "D:\LPHK\logger.py", line 36, in write
    self._file.write(data)
  File "C:\Users\dunca\Miniconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 37-39: character maps to <undefined>
```

what happens is that the schedulers break, my MK2 responds perfectly fine after pressing the gray button

**Comment by RealCountrx** [comment]
Okay. What can I use as an alternitave?

**Comment by duncte123** [comment]
Well don't try to type the invalid characters, you can also add the async header to not break the main thread for the scripts

**Comment by RealCountrx** [comment]
Alright. Thank you!
