### ISSUE TITLE
This is a really great project but the documentation was hard for me to make sense of. 

### ISSUE THREAD

**Issue by matdombrock** [nimaid/LPHK#9]
@nimaid, Now that I've got the hang of how to use this, would you be open to a PR with some more user friendly instructions when I have the time?

**Comment by nimaid** [comment]
Sure, when you're ready show me what you've got and I'll look it over. :) Be advised installation will be greatly improved soon via an installer executable.

**Comment by nimaid** [comment]
@matdombrock If could please start a discussion on the Discord, I could close this issue.

**Comment by matdombrock** [comment]
Sorry, it's been a really long time since I've touched this project so I'm
not sure that I would still be a good candidate to do a PR.
-Mathieu Dombrock
-------
360.224.8958
https://mzero.space <http://mzero.space> (Website)

**Comment by nimaid** [comment]
@matdombrock It's up to you if you'd like to contribute or not. If you do want to help with documentation and PR stuff, Please join the DIscord and start a conversation in #project-chat. Hope to see you around regardless. :)
